### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by patrickpissurno** [valoeghese/Nocreeperholes#1]
Hi. Could you please update it to 1.17?

Thanks!

**Comment by gniftygnome** [comment]
I've updated the build for 1.17.1 and it's testing out fine so far.  Updated source is at:  [gniftygnome / Nocreeperholes](https://github.com/gniftygnome/Nocreeperholes)

**Comment by gniftygnome** [comment]
P.S.  This mod is indispensable for long-term technical play.  If Mojang was serious about supporting technical players, this functionality would be in vanilla.  Nocreeperholes is an incredibly simple, well-written mod that really showcases the beauty of the fabric modding system.  I wish I had found it earlier in the 1.16 cycle, but in part I think the name does not cover enough of what the mod does.

**Comment by valoeghese** [comment]
I finally spent the like 10 minutes needed to update this to 1.17.1 lol... I actually had forgotten about this, sorry 😅
